import React from 'react';
import { AbsoluteFill, Audio, getStaticFiles, staticFile, useCurrentFrame } from 'remotion';
import { AUDIO, COLORS, LOOK } from './config';
import { Grain, Vignette } from './components/Atmosphere';
import { Captions } from './components/Captions';
import { FilmTextProvider, useLang } from './i18n/copy';
import { EASE, pulse, ramp } from './lib/motion';
import { FilmTimeProvider } from './lib/timing';
import { alpha } from './lib/util';
import type { PromoProps } from './props';
import { MasterScenes } from './Promo';
import { EDITS, editTime, shotStart, type EditId } from './timeline/edits';

/** A white-blue exposure flash on shots that enter with `flash`. */
const ShotTransitions: React.FC<{ edit: EditId }> = ({ edit }) => {
  const out = useCurrentFrame();
  const e = EDITS[edit];
  let flash = 0;
  e.shots.forEach((s, i) => {
    if (i === 0) return;
    const at = shotStart(e, i);
    // SFX: the soundtrack places a short whoosh on every cut.
    flash = Math.max(flash, s.enter === 'flash' ? pulse(out, at - 3, at + 14, 0.2) : pulse(out, at - 1, at + 4, 0.25) * 0.25);
  });
  if (flash <= 0) return null;
  return <AbsoluteFill style={{ background: `radial-gradient(circle at 50% 50%, rgba(255,255,255,${0.55 * flash}), ${alpha(COLORS.accent, 0.35 * flash)} 60%, ${alpha(COLORS.accent, 0.15 * flash)})` }} />;
};

const Soundtrack: React.FC<{ edit: EditId }> = ({ edit }) => {
  const { lang } = useLang();
  if (!AUDIO.enabled) return null;
  // Generated by `npm run audio`; each language has its own mix (the taps
  // follow that language's screen recordings). Silent if not generated yet.
  const files = new Set(getStaticFiles().map((f) => f.name));
  const file = [`audio/${edit}-${lang}.m4a`, `audio/${edit}.m4a`].find((f) => files.has(f));
  if (!file) return null;
  return <Audio src={staticFile(file)} volume={AUDIO.masterVolume} />;
};

const FilmBody: React.FC<{ edit: EditId; captions: boolean }> = ({ edit, captions }) => {
  const out = useCurrentFrame();
  const { rtl } = useLang();
  const e = EDITS[edit];
  const t = editTime(e, out);
  const fadeOut = LOOK.fadeOutFrames > 0 ? ramp(out, e.frames - LOOK.fadeOutFrames, e.frames - 1, 0, 1, EASE.smooth) : 0;
  return (
    <AbsoluteFill style={{ backgroundColor: '#000', direction: rtl ? 'rtl' : 'ltr' }}>
      <FilmTimeProvider value={{ master: t.master, step: t.step }}>
        <MasterScenes />
      </FilmTimeProvider>
      <ShotTransitions edit={edit} />
      <Grain />
      <Vignette />
      {captions && <Captions edit={edit} />}
      {fadeOut > 0 && <AbsoluteFill style={{ background: '#000', opacity: fadeOut }} />}
      <Soundtrack edit={edit} />
    </AbsoluteFill>
  );
};

/** One cut of the film. Every composition renders through this. */
export const Film: React.FC<PromoProps & { edit: EditId }> = ({ edit, lang, captions, prospect }) => (
  <FilmTextProvider lang={lang} prospect={prospect}>
    <FilmBody edit={edit} captions={captions} />
  </FilmTextProvider>
);

export const FilmFull: React.FC<PromoProps> = (p) => <Film {...p} edit="full" />;
export const Film15: React.FC<PromoProps> = (p) => <Film {...p} edit="cut15" />;
export const Film6: React.FC<PromoProps> = (p) => <Film {...p} edit="cut6" />;
