// BrandMark.jsx — the TeamMart logo from the shared brand kit (/brand).
// The SVGs in assets/brand/ are generated by brand/tools/build.py; change
// the kit and re-run it rather than editing these copies.
//
// Blue is the brand's identity color (logo, data); orange stays the app's
// action color (buttons, active states, alerts). See brand/README.md.
import markUrl from "../../assets/brand/teammart-mark.svg";
import wordmarkUrl from "../../assets/brand/teammart-wordmark-on-dark.svg";

export function BrandMark({ className = "h-9 w-9", glow = true }) {
  return (
    <img
      src={markUrl}
      alt=""
      aria-hidden="true"
      draggable="false"
      className={`shrink-0 select-none ${glow ? "drop-shadow-[0_0_14px_rgba(79,124,255,0.45)]" : ""} ${className}`}
    />
  );
}

export function BrandWordmark({ className = "h-[15px]" }) {
  return <img src={wordmarkUrl} alt="TeamMart" draggable="false" className={`block w-auto select-none ${className}`} />;
}
